name: build.yml

on: [ push, pull_request ]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup (MacOS)
      run:  ./scripts/setup_macos.sh
      if:   matrix.os == 'macos-latest'

    - name: Setup (Ubuntu)
      run:  ./scripts/setup_ubuntu.sh
      if:   matrix.os == 'ubuntu-latest'

    - name: Build (MacOS)
      run:  ./scripts/build_macos.sh
      if:   matrix.os == 'macos-latest'

    - name: Build (Ubuntu)
      run:  ./scripts/build_ubuntu.sh
      if:   matrix.os == 'ubuntu-latest'
