name: build.yml

on: [push, pull_request]

jobs:

  build:

    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup (MacOS)
      if:   matrix.os == 'macos-latest'
      run:  ./scripts/setup_macos.sh

    - name: Setup (Ubuntu)
      if:   matrix.os == 'ubuntu-latest'
      run:  ./scripts/setup_ubuntu.sh

    - name: Setup (Windows)
      if:   matrix.os == 'windows-latest'
      run:  cmd /c ".\scripts\setup_windows.bat"

    - name: Build (MacOS)
      if:   matrix.os == 'macos-latest'
      run:  ./scripts/build_macos.sh

    - name: Build (Ubuntu)
      if:   matrix.os == 'ubuntu-latest'
      run:  ./scripts/build_ubuntu.sh

    - name: Build (Windows)
      if:   matrix.os == 'windows-latest'
      run:  cmd /c ".\scripts\build_windows.bat"

    - name: Archive build artefacts
      if:   github.event_name == 'push'
      uses: actions/upload-artifact@master
      with:
        name: StftPitchShiftPlugin-${{matrix.os}}
        path: ./build/StftPitchShiftPlugin_artefacts/Release
